### ISSUE TITLE
Feature Request: createVisitObject

### ISSUE THREAD

**Issue by muco-rolle** [unirakun/graphql-directives-middlewares#5]
First all thank you for this package, can you please add other directives implemention like 

`createVisitObject`

so that we could add directives on object location 

```js
type Query @auth {
        posts: [Post!]!
}

type Mutation @auth {
       createPost(post: CreatePostInput): Post!
}
```

**Comment by fabienjuif** [comment]
Hello @muco-rolle  👋 

Thank your for your interest.
The first thing I want to know is : do you think you can do a PR to write this?

It would help me I think :)

**Comment by fabienjuif** [comment]
@muco-rolle you can install the version 0.2.0 right now from npm 👍 

https://github.com/unirakun/graphql-directives-middlewares/releases/tag/v0.2.0
